# Tắt hiển thị Swagger và các API Docs public trên Prod
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Tắt hibernate SQL log để tối ưu hiệu suất (giống tắt debug level ở Gunicorn)
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web=ERROR
